### PR TITLE
sync: merge upstream `master` into forked `master`

### PR DESCRIPTION
**Pull request by georglauterbach**
This PR synchronizes our `master` branch with Sway's official upstream `master` branch.

#### What Did I Do?

1. Created a fork of my own from this repository
2. Added Sway as a new upstream
3. Merged the upstream `master` into my `master`
4. Opened this PR

CC @SoumyaRanjanPatnaik

### CODE REVIEW

**Comment by georglauterbach** [comment]
@kgilmer pinging you here to see what the current status is; not sure whether we can merge this as-is (in the sense that it doesn't break Regolith functionality), but it'd be nice to be up-to-date with upstream I guess

**Comment by kgilmer** [comment]
Hi @georglauterbach , thanks for the bump. We're on the home stretch of the 3.0 release and so we'll take this up once that's out the door.  Thanks!

**Comment by georglauterbach** [comment]
Sounds awesome - can't wait to go v3 :D

**Comment by georglauterbach** [comment]
I rebased onto official upstream again to catch the latest changes. All in all, I had two or thre merge conflicts that I resolved; we may want to have a look at the last commits that I had to touch.

**Comment by SoumyaRanjanPatnaik** [comment]
Thanks for the PR. This will be useful when sway 1.9 is released and packaged :)

**Comment by kgilmer** [comment]
any reason why we shouldn't build this change into the `unstable` stage @SoumyaRanjanPatnaik ?  Currently we're building this branch: https://github.com/regolith-linux/voulage/blob/main/stage/unstable/package-model.json#L193

**Comment by SoumyaRanjanPatnaik** [comment]
The master branch is in sync with `v1.9-dev` of sway. Ubuntu ships `v1.7` of sway. Sway releases typically change the dependencies quite drastically, so it would make sense to wait till the maintainers of sway release a source package so we can steal the list of dependencies. Building `v1.8` or `v1.9` with the current control file doesn't work.

**Pull request merged**
